<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>
<h1 style="display:none;">Test</h1>

# Introduction to Databases: Moneyball Continued

## Some Helper Code

In [1]:
%load_ext sql

- Test helper code.

In [2]:

%sql mysql+pymysql://root:sh01dan5@localhost/lahman2016

%sql select * from master where playerid='willite01'

1 rows affected.

[('willite01', 1918, 8, 30, 'USA', 'CA', 'San Diego', '2002', '7', '5', 'USA', 'FL', 'Inverness', 'Ted', 'Williams', 'Theodore Samuel', 205, 75, 'L', 'R', '1939-04-20', '1960-09-28', 'willt103', 'willite01')]

In [3]:
import dbhelper

In [4]:
bat = % sql select * from batting where yearid>=2010
bat_df = bat.DataFrame()
bat_df.tail(10)

9966 rows affected.

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
9956,zobribe01,2015,1,OAK,AL,67,235,39,63,20,...,33,1,1,33,26,2,0,0,3,5
9957,zobribe01,2015,2,KCA,AL,59,232,37,66,16,...,23,2,3,29,30,1,1,0,2,3
9958,zobribe01,2016,1,CHN,NL,147,523,94,142,31,...,76,6,4,96,82,6,4,4,4,17
9959,zumayjo01,2010,1,DET,AL,31,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9960,zuninmi01,2013,1,SEA,AL,52,173,22,37,5,...,14,1,0,16,49,0,3,0,1,5
9961,zuninmi01,2014,1,SEA,AL,131,438,51,87,20,...,60,0,3,17,158,1,17,0,4,12
9962,zuninmi01,2015,1,SEA,AL,112,350,28,61,11,...,28,0,1,21,132,0,5,8,2,6
9963,zuninmi01,2016,1,SEA,AL,55,164,16,34,7,...,31,0,0,21,65,0,6,0,1,0
9964,zychto01,2015,1,SEA,AL,13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9965,zychto01,2016,1,SEA,AL,12,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
import pandas as pd
bat_g = bat_df.groupby("playerID")

In [45]:
bat_g_combined=pd.DataFrame()
bat_g_combined["H"] = bat_g['H'].sum()
bat_g_combined["HR"] = bat_g['HR'].sum()
bat_g_combined["2B"] = bat_g['2B'].sum()
bat_g_combined["3B"] = bat_g['3B'].sum()
bat_g_combined["1B"] = bat_g_combined['H']-bat_g_combined['2B']-bat_g_combined['3B']-bat_g_combined['HR']
bat_g_combined["AB"] = bat_g["AB"].sum()
bat_g_combined["SLP"] = (bat_g_combined['1B']+bat_g_combined['2B']*2+bat_g_combined['3B']*3+bat_g_combined['HR']*4) \
    / bat_g_combined["AB"]

In [49]:
bat_g_combined = bat_g_combined.sort_values('SLP',ascending=False)
bat_g_combined[bat_g_combined["AB"] > 500]

              H   HR   2B  3B   1B    AB       SLP
playerID
cabremi01  1299  237  270   5  787  3932  0.582401
ortizda01  1014  224  252   5  533  3468  0.561707
troutmi01   917  168  175  37  537  2997  0.557224
bautijo02   893  249  177   9  458  3385  0.542097
stantmi03   792  208  170  10  404  2980  0.538926
vottojo01  1073  168  233  12  660  3422  0.535944
gonzaca01  1000  184  197  28  591  3375  0.534815
braunry02  1074  182  213  24  655  3552  0.529561
cruzne02   1027  229  203   8  587  3664  0.527566
thomeji01   190   48   39   2  101   716  0.526536
encared01   940  231  197   3  509  3491  0.525924
goldspa01   844  140  198  11  495  2824  0.525496
bryankr01   330   65   66   8  191  1162  0.522375
beltrad01  1242  195  243  10  794  4010  0.521197
arenano01   613  111  141  16  345  2152  0.519981
hamiljo03   767  139  163  15  450  2651  0.519427
seageco01   226   30   48   6  142   725  0.518621
tulowtr01   869  152  169   8  540  2927  0.515887
abreujo02   537   91  101   6  339  1793  0.514780
canoro01   1335  191  280  16  848  4355  0.509759
dickeco01   380   63   94  16  207  1364  0.509531
daviskh01   394  102   87   6  199  1584  0.504419
donaljo02   748  141  158  12  437  2690  0.502974
pujolal01  1108  225  215   2  666  3992  0.501503
davisch02   745  203  151   1  390  3007  0.501164
harpebr03   651  121  122  17  391  2336  0.500856
bettsmo01   443   54   96  14  279  1458  0.500000
grichra01   223   44   58  11  110   879  0.494881
kempma01   1018  179  203  18  618  3630  0.494215
cespeyo01   743  137  149  22  435  2728  0.493768
...         ...  ...  ...  ..  ...   ...       ...
crowetr01   153    3   32   4  114   635  0.318110
bartlja01   266    6   54   6  200  1108  0.315884
vizquom01   173    2   23   3  145   664  0.313253
sogarer01   289    8   52   7  222  1210  0.313223
sanchan02   139    1   19   4  115   543  0.311234
schafjo02   261   10   40   9  202  1125  0.310222
wilsojo03   141    5   27   3  106   611  0.309329
cruzto03    130    5   32   3   90   595  0.307563
stewach01   236    9   39   0  188   990  0.305051
tholejo01   306    9   51   2  244  1283  0.302416
robinsh01   149    6   21   5  117   655  0.302290
mathije01   251   25   53   4  169  1289  0.300233
gwynnto02   215    5   31  14  165   965  0.299482
quintom01   118    6   18   3   91   535  0.299065
brignre01   169   11   28   2  128   786  0.297710
treanma01   110   10   15   2   83   536  0.296642
floripe01   134   10   25   5   94   671  0.296572
buterdr01   178   13   40   4  121   897  0.295429
rominan01   183    6   19   2  156   761  0.294350
getzch01    252    1   32   7  212  1027  0.293087
kozmape01   138    3   29   3  103   621  0.293076
gonzaal03   123    2   22   4   95   544  0.292279
kawasmu01   150    1   18   6  125   633  0.289100
ryanbr01    390   12   79  11  288  1824  0.288925
marsolo01   151    4   32   4  111   703  0.288762
janispa01   178    5   36   2  135   810  0.287654
figgich01   253    4   40   5  204  1116  0.282258
izturce01   182    3   28   3  148   798  0.281955
martimi02   105    6   15   2   82   534  0.265918
bakerjo01   106    0   18   1   87   506  0.249012

[599 rows x 7 columns]

In [66]:
t = bat_g_combined['AB']>2000
t2 = bat_g_combined['H']>1000
bat_g_combined[t2 & t].sort_values('SLP',ascending=False)

              H   HR   2B  3B   1B    AB       SLP
playerID
cabremi01  1299  237  270   5  787  3932  0.582401
ortizda01  1014  224  252   5  533  3468  0.561707
vottojo01  1073  168  233  12  660  3422  0.535944
braunry02  1074  182  213  24  655  3552  0.529561
cruzne02   1027  229  203   8  587  3664  0.527566
beltrad01  1242  195  243  10  794  4010  0.521197
canoro01   1335  191  280  16  848  4355  0.509759
pujolal01  1108  225  215   2  666  3992  0.501503
kempma01   1018  179  203  18  618  3630  0.494215
mccutan01  1180  163  236  33  748  4030  0.489082
gonzaad01  1230  171  262   4  793  4163  0.483546
longoev01  1025  181  227  15  602  3805  0.479632
poseybu01  1003  116  190   8  689  3261  0.477461
jonesad01  1188  194  199  16  779  4258  0.469939
uptonju01  1037  178  205  21  633  3877  0.468919
pencehu01  1048  140  193  29  686  3718  0.462345
pedrodu01  1103   91  230  11  771  3706  0.439288
kinslia01  1140  129  231  27  753  4137  0.437999
butlebi03  1078  107  226   2  743  3725  0.437315
altuvjo01  1046   60  204  19  763  3361  0.436775
cabreme01  1091   78  224  30  759  3707  0.434044
reyesjo01  1012   63  188  48  713  3470  0.427954
zobribe01  1032  103  250  27  652  3861  0.426055
desmoia01  1072  128  207  22  715  4023  0.424310
pradoma01  1163   81  229  22  831  4012  0.418495
phillbr01  1132  103  203  13  813  4022  0.415216
kendrho01  1067   73  205  26  763  3749  0.411576
castrst01  1147   83  215  32  817  4101  0.408437
markani01  1185   80  231   9  865  4177  0.400766
ramiral03  1098   79  213  14  792  4112  0.383268
aybarer01  1015   42  194  29  750  3758  0.370676
andruel01  1138   29  190  29  890  4145  0.355368
escobal02  1065   30  163  45  827  4094  0.343918